/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c DBusServiceIfAdaptor -a dbusserviceifadaptor.h:dbusserviceifadaptor.cpp com.meego.mssf.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbusserviceifadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DBusServiceIfAdaptor
 */

DBusServiceIfAdaptor::DBusServiceIfAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DBusServiceIfAdaptor::~DBusServiceIfAdaptor()
{
    // destructor
}

bool DBusServiceIfAdaptor::setState(int state)
{
    // handle method call com.meego.mssf.setState
    bool out0;
    QMetaObject::invokeMethod(parent(), "setState", Q_RETURN_ARG(bool, out0), Q_ARG(int, state));
    return out0;
}

